import type { Recipe } from '@/types/recipe'

// TO DO: 
// - need source for: baked salmon
// - maybe change the format of cooktime to hours and minutes instead of just minutes?

export const MOCK_RECIPES: Recipe[] = [
  // TO UPDATE: source, sourceUrl
  {
    id: '1',
    title: 'Burrito Wrap',
    image: '/burrito-wrap.webp',
    cuisines: ['Mexican'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 40,
    servings: 6,
    rating: 4.8,
    source: 'New York Times Cooking',
    sourceUrl: 'https://cooking.nytimes.com/recipes/1024725-easy-burritos',
    ingredients: [
      { quantity: 1, unit: 'pound', item: 'ground beef' },
      { quantity: 1, unit: '', item: 'medium yellow or white onion, finely chopped' },
      { quantity: 1.5, unit: 'teaspoons', item: 'ground cumin' },
      { quantity: 0.5, unit: 'teaspoon', item: 'smoked paprika, or chipotle or ancho chile powder' },
      { quantity: 0.5, unit: 'teaspoon', item: 'dried oregano' },
      { quantity: 1, unit: 'can (15-ounce)', item: 'black or pinto beans' },
      { quantity: 1, unit: '', item: 'large tomato, coarsely chopped' },
      { quantity: 2, unit: 'teaspoons', item: 'lime juice, or apple cider vinegar' },
      { quantity: null, unit: '', item: 'Hot sauce, for drizzling (optional)' },
      { quantity: 6, unit: '', item: 'burrito-size (about 10-inch) flour tortillas' },
      { quantity: 2, unit: 'cups', item: 'shredded Monterey Jack or Mexican blend cheese (8 ounces)' }
    ],
    instructions: [
      'In a large skillet, press the beef into an even layer to fill the skillet. Sprinkle with the onion. Cook over medium-high, undisturbed, until the meat is deeply browned underneath, 6 to 8 minutes.',
      'Sprinkle with the cumin, smoked paprika and oregano, and season with salt and pepper. Break up the beef into small pieces, then cook, stirring occasionally, until the onion is softened and the spices are fragrant, 2 to 4 minutes.',
      'Add the beans, including the liquid, and the tomato and simmer, stirring and scraping up browned bits, until the liquid has evaporated and the mixture starts to sizzle, 8 to 10 minutes. Turn off the heat, stir in the lime juice and season with salt and pepper.',
      'Arrange the tortillas on a clean work surface. Sprinkle half the cheese across the center of the tortillas, left to right, leaving a 1-inch border. Top each with ⅔ cup of the beef-bean mixture, followed by the remaining cheese. Drizzle on hot sauce, if using.',
      'Fold the tortilla’s short sides over the filling, then fold the bottom of the tortilla snugly over the filling. Tightly roll away from you until the burrito is sealed. Repeat with the other tortillas.',
      'When ready to eat, in a nonstick skillet over medium, place the burritos seam side down. Cook, turning occasionally, until golden all over, 3 to 5 minutes. Serve with desired toppings.',
    ],
    dietaryTags: ['Nut-Free'],
    healthTags: [],
  },

  {
    id: '2',
    title: 'Pokebowl',
    image: '/pokebowl.jpg',
    cuisines: ['Italian'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 4,
    rating: 4.8,
    source: 'Jessica Gavin',
    sourceUrl: 'https://www.jessicagavin.com/ahi-tuna-poke-bowl-recipe/',
    ingredients: [
      { quantity: 1, unit: 'lb', item: 'sushi-grade ahi tuna, cut into ~¾-inch cubes' },
      { quantity: 0.25, unit: 'cup', item: 'soy sauce' },
      { quantity: 1, unit: 'tsp', item: 'rice vinegar' },
      { quantity: 1.5, unit: 'tsp', item: 'sesame oil' },
      { quantity: 0.75, unit: 'tsp', item: 'red pepper flakes (crushed)' },
      { quantity: 0.33, unit: 'cup', item: 'green onions (thinly sliced)' },
      { quantity: 0.5, unit: 'tsp', item: 'sesame seeds (plus more for garnish)' },
      { quantity: 2, unit: 'cups', item: 'cooked brown rice (or white rice)' },
      { quantity: 2, unit: 'cups', item: 'salad greens' }
    ],
    instructions: [
      'Cook the rice: Rinse and cook the rice per the manufacturer’s instructions.',
      'Marinate the tuna: In a bowl, combine the tuna cubes, soy sauce, rice vinegar, sesame oil, red pepper flakes, green onions, and sesame seeds. Mix so the marinade coats the tuna.',
      'Assemble the bowls: Divide the cooked rice and salad greens into bowls. Top with the marinated tuna (either immediately after mixing, or after marinating 15-30 minutes for deeper flavor).',
      'Add toppings & serve: Garnish with extra sesame seeds and desired toppings (avocado, cucumber, seaweed, etc.). Serve right away.'
    ],
    dietaryTags: ['Nut-Free', 'Dairy-Free'],
    healthTags: [],
  },
  {
    id: '3',
    title: 'Lasagna',
    image: '/lasagna.jpg',
    cuisines: ['Italian'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 4,
    rating: 4.8,
    source: 'spend with pennies',
    sourceUrl: 'https://www.spendwithpennies.com/easy-homemade-lasagna/#wprm-recipe-container-145181',
    ingredients: [
      { quantity: 12, unit: '', item: 'uncooked lasagna noodles' },
      { quantity: 4, unit: 'cups', item: 'shredded mozzarella cheese divided' },
      { quantity: 0.5, unit: 'cup', item: 'shredded Parmesan cheese shredded and divided' },
      { quantity: 0.75, unit: 'teaspoon', item: 'salt' },
      { quantity: 0.5, unit: 'pound', item: 'lean ground beef' },
      { quantity: 0.5, unit: 'pound', item: 'Italian sausage' },
      { quantity: 1, unit: '', item: 'yellow onion diced' },
      { quantity: 36, unit: 'ounces', item: 'pasta sauce' },
      { quantity: 2, unit: 'tablespoons', item: 'tomato sauce' },
      { quantity: 1, unit: 'teaspoon', item: 'Italian seasoning' },
      { quantity: 2, unit: 'cups', item: 'ricotta cheese or cottage cheese' },
      { quantity: 0.25, unit: 'cup', item: 'chopped fresh parsley' },
      { quantity: 1, unit: '', item: 'large egg beaten' }
    ],
    instructions: [
     'Preheat the oven to 350°F. Bring a large pot of salted water to a boil. Add the lasagna noodles and cook until al dente (firm) according to package directions. Drain, rinse under cold water, and set aside.',
     'Meanwhile, in a large skillet or Dutch oven, brown the beef, sausage, onion, and garlic over medium-high heat until no pink remains. Drain any fat.',
     'Stir in the pasta sauce, tomato paste, Italian seasoning, ½ teaspoon of salt, and ¼ teaspoon of black pepper. Simmer uncovered over medium heat for 5 minutes or until slightly thickened. Taste and season with additional salt if desired.',
     'In a separate medium bowl, combine 1 ½ cups mozzarella cheese, ¼ cup parmesan cheese, ricotta, parsley, egg, and ¼ teaspoon salt.',
     'Spread 1 cup of the meat sauce in a 9×13 pan or casserole dish. Top it with 3 lasagna noodles. Layer with ⅓ of the ricotta cheese mixture and 1 cup of meat sauce. Repeat twice more. Finish with 3 noodles topped with remaining sauce.',
     'Cover with foil and bake for 45 minutes.',
     'Remove the foil and sprinkle the top of the lasagna with the remaining 2 ½ cups mozzarella cheese and ¼ cup parmesan cheese. Bake uncovered for an additional 15 minutes or until browned and bubbly. Broil for 2-3 minutes if desired.',
     'Rest for at least 15 minutes before cutting.'
    ],
    dietaryTags: ['Nut-Free'],
    healthTags: [],
  },

  { // in the google doc, this is categorized as "seafood"; need to implement that cuisine category in our questionnaire
    // TO UPDATE: source, sourceUrl
    id: '4',
    title: 'Baked Salmon',
    image: '/baked-salmon.jpg',
    cuisines: ['American'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 4,
    rating: 4.8,
    source: 'Food Blogger Pro',
    sourceUrl: 'https://example.com/recipe/margherita-pizza',
    ingredients: [
      { quantity: null, unit: '', item: 'Salmon fillets' },
      { quantity: null, unit: '', item: 'Olive oil' },
      { quantity: null, unit: '', item: 'Salt' },
      { quantity: null, unit: '', item: 'Cracked black pepper' },
      { quantity: null, unit: '', item: 'Minced garlic' },
      { quantity: null, unit: '', item: 'Italian herb seasoning blend (or herbs de provence)' },
      { quantity: null, unit: '', item: 'Lemon' }
    ],
    instructions: [
      'Preheat the oven to 400 degrees and grease a large baking pan. Arrange the salmon fillets on the baking sheet and season generously with salt and pepper.',
      'Stir together the olive oil, garlic, herbs, and juice of 1/2 of the lemon. Spoon this sauce over salmon fillets, being sure to rub all over the tops and sides of the salmon so it has no dry spots. Thinly slice the remaining 1/2 of the lemon and top each piece of salmon with a slice of lemon.',
      'Bake the salmon in the oven for 12-15 minutes or until the salmon is opaque and flaky when pulled apart with a fork. You can broil the last 1-2 minutes if desired.',
      'Garnish with fresh thyme or parsley if desired and serve.'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free'],
    healthTags: [],
  },

  {
    id: '5',
    title: 'Tikka Masala', 
    image: '/tikka-masala.jpg',
    cuisines: ['Asian'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 6,
    rating: 4.8,
    source: 'All Recipes',
    sourceUrl: 'https://www.allrecipes.com/recipe/228293/curry-stand-chicken-tikka-masala-sauce/',
    ingredients: [
      { quantity: 2, unit: 'tablespoons', item: 'ghee (clarified butter)' },
      { quantity: 1, unit: '', item: 'onion, finely chopped' },
      { quantity: 4, unit: 'cloves', item: 'garlic, minced' },
      { quantity: 1, unit: 'tablespoon', item: 'ground cumin' },
      { quantity: 1, unit: 'teaspoon', item: 'salt, or more to taste (Optional)' },
      { quantity: 1, unit: 'teaspoon', item: 'ground ginger' },
      { quantity: 1, unit: 'teaspoon', item: 'cayenne pepper' },
      { quantity: 0.5, unit: 'teaspoon', item: 'ground cinnamon' },
      { quantity: 0.25, unit: 'teaspoon', item: 'ground turmeric' },
      { quantity: 1, unit: 'can (14 ounce)', item: 'tomato sauce' },
      { quantity: 1, unit: 'cup', item: 'heavy whipping cream' },
      { quantity: 1, unit: 'tablespoon', item: 'white sugar, or more to taste (Optional)' },
      { quantity: 2, unit: 'teaspoons', item: 'paprika' },
      { quantity: 1, unit: 'tablespoon', item: 'vegetable oil' },
      { quantity: 4, unit: '', item: 'skinless, boneless chicken breast halves, cut into bite-size pieces' },
      { quantity: 0.5, unit: 'teaspoon', item: 'curry powder' }
    ],
    instructions: [
      'Heat ghee in a large skillet over medium heat. Add onion; cook and stir until translucent, about 5 minutes.',
      'Stir in garlic; cook and stir just until fragrant, about 1 minute. Stir cumin, 1 teaspoon salt, ginger, cayenne pepper, cinnamon, and turmeric into onion mixture; fry until fragrant, about 2 minutes.',
      'Stir tomato sauce into onion and spice mixture; bring to a boil and reduce heat to low.',
      'Simmer sauce for 10 minutes, then mix in cream, 1 tablespoon sugar, and paprika. Bring sauce back to a simmer and cook, stirring often, until sauce is thickened, 10 to 15 minutes.',
      'Heat vegetable oil in a separate skillet over medium heat. Stir chicken into hot oil; add curry powder. Sear chicken until lightly browned but still pink inside, about 3 minutes; stir often.',
      'Transfer chicken and any pan juices into sauce. Simmer chicken in sauce until no longer pink, about 30 minutes; adjust sugar and salt to taste.'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free'],
    healthTags: [],
  },

  {
    // TO UPDATE: mealPrepDuration, servings, dietaryTags, healthTags
    id: '6',
    title: 'Pho',
    image: '/pho.webp',
    cuisines: ['Asian'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 4,
    rating: 4.8,
    source: 'The Forked Spoon',
    sourceUrl: 'https://theforkedspoon.com/pho-recipe/',
    ingredients: [
      { quantity: null, unit: '', item: 'Marrow bones and meaty bones' },
      { quantity: null, unit: '', item: 'Thinly sliced raw meat' },
      { quantity: null, unit: '', item: 'Yellow onions' },
      { quantity: null, unit: '', item: 'Whole garlic' },
      { quantity: null, unit: '', item: 'Fresh ginger' },
      { quantity: null, unit: '', item: 'Whole spices: star anise, cloves, cinnamon sticks, black cardamom pods, fennel seeds' },
      { quantity: null, unit: '', item: 'Coriander seeds' },
      { quantity: null, unit: '', item: 'Salt' },
      { quantity: null, unit: '', item: 'Fish sauce' },
      { quantity: null, unit: '', item: 'Sugar' },
      { quantity: null, unit: '', item: 'Fresh mint' },
      { quantity: null, unit: '', item: 'Sprigs of Thai basil' },
      { quantity: null, unit: '', item: 'Fresh cilantro' },
      { quantity: null, unit: '', item: 'Green onions' },
      { quantity: null, unit: '', item: 'Sliced white or red onion' },
      { quantity: null, unit: '', item: 'Fresh lime wedges' },
      { quantity: null, unit: '', item: 'Mung bean sprouts' },
      { quantity: null, unit: '', item: 'Sliced Thai red chiles' },
      { quantity: null, unit: '', item: 'Cabbage' },
      { quantity: null, unit: '', item: 'Bok choy' },
      { quantity: null, unit: '', item: 'Sliced jalapeño' },
      { quantity: null, unit: '', item: 'Sriracha or other spicy chili sauces' },
      { quantity: null, unit: '', item: 'Hoisin sauce' }
    ],
    instructions: [
      'Pick a large enough bowl. YOU GUYS, Vietnamese noodle soup needs big bowls. Cereal bowls will not work here. Between the noodles and the broth and the veggies, bowls fill up fast.',
      'Rice noodles first. Add your pre-cooked noodles first. My husband loves a whole lot of noodles, whereas I love extra veggies. Fill your bowl appropriately.',
      'Raw meat next. Yes, you guys. RAW. Totally, completely uncooked (see above). Remember how I mentioned slicing your beef super (paper) thin? This is why. Don’t worry, assuming your broth is boiling hot and not just warm, your meat will get fully cooked.',
      'Add the broth. It doesn’t matter which broth (the fast or the slow method), this is the moment. Just make sure it’s super hot.',
      'Garnish like crazy. Add cooked beef from the bones you used to make the bone broth, add one sauce…or five. Guys, it’s up to you! Have fun!'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free'],
    healthTags: [],
  },

  {
    id: '7',
    title: 'Indian Chicken Curry',
    image: '/indian-chicken-curry.jpg',
    cuisines: ['Asian'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 45,
    servings: 4,
    rating: 4.8,
    source: 'All Recipes',
    sourceUrl: 'https://www.allrecipes.com/recipe/46822/indian-chicken-curry-ii/',
    ingredients: [
      { quantity: 2, unit: 'tablespoons', item: 'olive oil' },
      { quantity: 1, unit: '', item: 'small onion, chopped' },
      { quantity: 2, unit: 'cloves', item: 'garlic, minced' },
      { quantity: 3, unit: 'tablespoons', item: 'curry powder' },
      { quantity: 1, unit: 'teaspoon', item: 'ground cinnamon' },
      { quantity: 1, unit: 'teaspoon', item: 'paprika' },
      { quantity: 1, unit: '', item: 'bay leaf' },
      { quantity: 0.5, unit: 'teaspoon', item: 'grated fresh ginger root' },
      { quantity: 0.5, unit: 'teaspoon', item: 'white sugar' },
      { quantity: null, unit: '', item: 'Salt to taste' },
      { quantity: 2, unit: '', item: 'skinlessm boneless chicken breast halves, cut into bite-sized pieces' },
      { quantity: 1, unit: 'tablespoon', item: 'tomato paste' },
      { quantity: 1, unit: 'cup', item: 'plain yogurt' },
      { quantity: 0.75, unit: 'cup', item: 'coconut milk' },
      { quantity: 0.5, unit: 'lemon', item: 'juiced' },
      { quantity: 0.5, unit: 'teaspoon', item: 'cayenne pepper' }
    ],
    instructions: [
      'Heat olive oil in a skillet over medium heat. Sauté onion until lightly browned.',
      'Stir in garlic, curry powder, cinnamon, paprika, bay leaf, ginger, sugar, and salt. Continue stirring for 2 minutes.',
      'Add chicken pieces, tomato paste, yogurt, and coconut milk. Bring to a boil, reduce heat, and simmer for 20 to 25 minutes.',
      'Remove bay leaf, and stir in lemon juice and cayenne pepper. Simmer 5 more minutes.'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free'],
    healthTags: [],
  },

  {
    id: '8',
    title: 'Caesar salad',
    image: '/caesar-salad.jpg',
    cuisines: ['American'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 4,
    rating: 4.8,
    source: 'Natasha\'s Kitchen',
    sourceUrl: 'https://natashaskitchen.com/caesar-salad-recipe/',
    ingredients: [
      { quantity: 1, unit: '', item: 'large or 2 small heads of Romaine lettuce' },
      { quantity: null, unit: '', item: 'Parmesan cheese, grated/shredded/shaved' },
      { quantity: null, unit: '', item: 'Crisp croutons' },
      { quantity: null, unit: '', item: 'Caesar dressing' }
    ],
    instructions: [
      'Rinse the lettuce in cold water.',
      'Chop, rinse, and spin dry the leaves to remove as much water as possible.',
      'Once the romaine is rinsed and dried, store it in an airtight container or a zip-top bag with a paper towel to absorb moisture,',
      'Add desired amount of croutons and mix.'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free'],
    healthTags: [],
  },

  {
    id: '9',
    title: 'Overnight Oats',
    image: '/overnight-oats.jpg',
    cuisines: ['American'],
    mealType: 'breakfast',
    mealPrepDuration: 1,
    difficulty: 'easy',
    cookTime: 480,
    servings: 1,
    rating: 4.8,
    source: 'Feel Good Foodie',
    sourceUrl: 'https://feelgoodfoodie.net/recipe/overnight-oats/#wprm-recipe-container-8144',
    ingredients: [
      { quantity: 0.5, unit: 'cup', item: 'rolled oats' },
      { quantity: 0.5, unit: 'cup', item: 'milk of choice' },
      { quantity: 0.25, unit: 'cup', item: 'Greek yogurt (non-fat)' },
      { quantity: 1, unit: 'Tbsp', item: 'chia seeds' },
      { quantity: 1, unit: 'Tbsp', item: 'sweetener (honey or maple syrup)' },
      { quantity: 0.25, unit: 'tsp', item: 'vanilla extract' }
    ],
    instructions: [
      'Place all ingredients (for the base and any chosen add-ins into a large glass container and mix until combined',
      'Cover the container with a lid or plastic wrap. Refrigerate for at least 2 hours or overnight. Add toppings either the night before or right before serving.',
      'Uncover and enjoy the next day. Thin with a little milk or water if desired.'
    ],
    dietaryTags: [],
    healthTags: ['High-Protein'],
  },

  {
    id: '10',
    title: 'Vanilla Berry Protein Smoothie',
    image: '/vanilla-berry-protein-smoothie.jpg',
    cuisines: ['American'],
    mealType: 'lunch',
    mealPrepDuration: 3,
    difficulty: 'easy',
    cookTime: 30,
    servings: 4,
    rating: 4.8,
    source: 'Tasty',
    sourceUrl: 'https://tasty.co/recipe/vanilla-berry-protein-smoothie',
    ingredients: [
      { quantity: 1.5, unit: 'cups', item: 'water, yogurt, or milk of choice' },
      { quantity: 1, unit: 'scoop', item: 'vanilla protein powder' },
      { quantity: 1, unit: 'cup', item: 'frozen strawberries' },
      { quantity: 1, unit: 'cup', item: 'frozen blueberries' },
      { quantity: 0.5, unit: 'cup', item: 'frozen raspberries' },
      { quantity: 0.5, unit: 'cup', item: 'frozen blackberries' }
    ],
    instructions: [
      'Put all ingredients into a blender.',
      'Mix until smooth.'
    ],
    dietaryTags: [],
    healthTags: ['High-Protein', 'Low-Cholesterol', 'Low-Fat', 'Vegetarian', 'Gluten-Free'],
  },

  {
    id: '11',
    title: 'Chia Pudding',
    image: '/chia-pudding.webp',
    cuisines: ['American'],
    mealType: 'breakfast',
    mealPrepDuration: 1,
    difficulty: 'easy',
    cookTime: 240,
    servings: 1,
    rating: 4.8,
    source: 'Downshiftology',
    sourceUrl: 'https://downshiftology.com/recipes/meal-prep-chia-pudding/',
    ingredients: [
      { quantity: 2, unit: 'tbsp', item: 'chia seeds' },
      { quantity: 0.5, unit: 'cup', item: 'milk (of your choice)' },
      { quantity: 1, unit: 'tsp', item: 'maple syrup or other sweetener (optional)' },
      { quantity: 1, unit: 'cup', item: 'frozen blueberries' },
      { quantity: 0.5, unit: 'cup', item: 'frozen raspberries' },
      { quantity: 0.5, unit: 'cup', item: 'frozen blackberries' }
    ],
    instructions: [
      'Add the chia seeds and milk into a small glass jar or container, then stir to combine.',
      'Let the mixture sit for about 15 minutes (chia seeds should begin to gel), then stir again.',
      'After it’s gelled, add your chosen toppings.',
      'Secure the container with a lid, then store it either in the refrigerator or freezer.'
    ],
    dietaryTags: ['Nut-Free'],
    healthTags: ['Low-Cholesterol', 'High-Fiber'],
  },

  {
    id: '12',
    title: 'Sheet Pan Omelette',
    image: '/sheet-pan-omelette.jpg',
    cuisines: ['American'],
    mealType: 'breakfast',
    mealPrepDuration: 2,
    difficulty: 'easy',
    cookTime: 25,
    servings: 3,
    rating: 4.8,
    source: 'The Recipe Well',
    sourceUrl: 'https://therecipewell.com/sheet-pan-omelette/#recipe',
    ingredients: [
      { quantity: 12, unit: '', item: 'large eggs' },
      { quantity: 0.33, unit: 'cup', item: 'cottage cheese' },
      { quantity: 0.33, unit: 'cup', item: 'milk (whole or 2%)' },
      { quantity: 0.5, unit: 'teaspoon', item: 'sea salt' },
      { quantity: 0.25, unit: 'teaspoon', item: 'black pepper' },
      { quantity: 0.5, unit: 'cup', item: 'fresh spinach, roughly chopped' },
      { quantity: 0.33, unit: 'cup', item: 'red bell pepper, thinly sliced' },
      { quantity: 0.33, unit: 'cup', item: 'feta cheese (or about ½ cup shredded cheddar)' }
    ],
    instructions: [
      'Preheat the oven to 350°F and grease a 14½ × 9½-inch jelly-roll (sheet) pan.',
      'In a large bowl, whisk together the eggs, cottage cheese, milk, salt, and pepper until fully blended.',
      'Pour the egg mixture into the prepared pan (be careful, the pan will be quite full).',
      'Evenly sprinkle the spinach, bell pepper, and feta (or your chosen cheese) on top of the egg mixture.',
      'Bake for 15–18 minutes, or until the eggs are firm and set (no longer jiggly).',
      'Once done, slice and serve with your desired sides.'
    ],
    dietaryTags: ['Gluten-Free', 'Nut-Free', 'Vegetarian'],
    healthTags: ['High-Protein', 'Low-Carb'],
  },

  {
    id: '13',
    title: 'French Toast Sticks',
    image: '/french-toast-sticks.jpg',
    cuisines: ['American'],
    mealType: 'breakfast',
    mealPrepDuration: 4,
    difficulty: 'easy',
    cookTime: 35,
    servings: 2,
    rating: 4.8,
    source: 'Tasty',
    sourceUrl: 'https://tasty.co/recipe/freezer-prep-french-toast-sticks',
    ingredients: [
      { quantity: 1, unit: 'loaf', item: 'Texas toast (or thick/sandwich bread)' },
      { quantity: 7, unit: '', item: 'large eggs' },
      { quantity: 1, unit: 'cup', item: 'milk' },
      { quantity: 3, unit: 'tbsp', item: 'butter, melted' },
      { quantity: 1, unit: 'tsp', item: 'vanilla extract' },
      { quantity: 2, unit: 'tbsp', item: 'sugar' },
      { quantity: null, unit: '', item: 'salt, to taste' },
      { quantity: null, unit: '', item: 'Cooking spray (to grease baking sheet)' }
    ],
    instructions: [
      'Preheat oven to 350°F (175°C).',
      'Spray a large baking sheet with cooking spray.',
      'Stack the bread slices and cut into thirds to form sticks.',
      'In a large bowl, whisk together eggs, milk, melted butter, vanilla, cinnamon, sugar, and salt.',
      'Dip each bread stick into the egg mixture, letting excess drip off. Place coated sticks on the prepared baking sheet.',
      'Bake for 15–20 minutes, flipping halfway through.',
      'Let cool slightly. Serve with warm syrup or toppings of choice.'
    ],
    dietaryTags: ['Nut-Free', 'Vegetarian'],
    healthTags: [],
  },

  {
    id: '14',
    title: 'Chicken Cajun Pasta',
    image: '/chicken-cajun-pasta.jpg',
    cuisines: ['American'],
    mealType: 'lunch',
    mealPrepDuration: 4,
    difficulty: 'medium',
    cookTime: 20,
    servings: 2,
    rating: 4.8,
    source: 'Budget Bytes',
    sourceUrl: 'https://www.budgetbytes.com/one-pot-creamy-cajun-chicken-pasta/',
    ingredients: [
      { quantity: null, unit: '', item: 'Cajun seasoning' },
      { quantity: 2, unit: 'tsp', item: 'smoked paprika' },
      { quantity: 1, unit: 'tsp', item: 'dried oregano' },
      { quantity: 0.5, unit: 'tsp', item: 'garlic powder' },
      { quantity: 0.5, unit: 'tsp', item: 'onion powder' },
      { quantity: 0.25, unit: 'tsp', item: 'cayenne pepper' },
      { quantity: 0.25, unit: 'tsp', item: 'black pepper' },
      { quantity: 0.25, unit: 'tsp', item: 'salt' },
      { quantity: 1, unit: 'Tbsp', item: 'olive oil' },
      { quantity: 1, unit: 'tbsp', item: 'butter' },
      { quantity: 1, unit: 'lb', item: 'boneless, skinless chicken breast, cubed' },
      { quantity: 1, unit: '', item: 'yellow onion, diced' },
      { quantity: 0.5, unit: 'lb', item: 'penne pasta (uncooked)' },
      { quantity: 15, unit: 'oz', item: 'fire-roasted diced tomatoes (with juices)' },
      { quantity: 2, unit: 'cups', item: 'chicken broth' },
      { quantity: 2, unit: 'oz', item: 'cream cheese' },
      { quantity: 3, unit: '', item: 'green onions, sliced (for garnish)' }
    ],
    instructions: [
     'Combine all the Cajun seasoning ingredients in a small bowl.',
     'Cut the chicken into ½- to ¾-inch cubes, then coat with the Cajun seasoning.',
     'Heat olive oil and butter in a large deep skillet over medium-high heat. Once hot and the butter is foamy, add the seasoned chicken. Sear the chicken on each side just until it gets some color (it doesn’t need to be fully cooked).',
     'Add the diced onion to the skillet; sauté for ~2 minutes, until the onion softens slightly.',
     'Bring the mixture to a boil, then lower heat to medium-low and simmer for about 10 minutes, stirring occasionally, until the pasta is tender and the liquid reduces into a thick, saucy consistency.',
     'Add the cream cheese in chunks, stirring until fully melted into the sauce.',
     'Top with sliced green onions and serve.'
    ],
    dietaryTags: ['Nut-Free'],
    healthTags: ['High-Protein']
  },

  {
    id: '15',
    title: 'Turkey Taco Bowl',
    image: '/turkey-taco-bowl.jpg',
    cuisines: ['Mexican'],
    mealType: 'breakfast',
    mealPrepDuration: 4,
    difficulty: 'medium',
    cookTime: 70,
    servings: 1,
    rating: 4.8,
    source: 'Sweet Peas and Saffron',
    sourceUrl: 'https://sweetpeasandsaffron.com/turkey-taco-lunch-bowls-meal-prep/',
    ingredients: [
      { quantity: 0.75, unit: 'cup', item: 'uncooked brown rice' },
      { quantity: 0.125, unit: 'tsp', item: 'salt (for the rice)' },
      { quantity: 1, unit: 'lime', item: 'Zest of lime' },
      { quantity: 0.75, unit: 'lb', item: 'lean ground turkey' },
      { quantity: 2, unit: 'Tbsp', item: 'taco seasoning (your choice)' },
      { quantity: 0.67, unit: 'cup', item: 'water' },
      { quantity: 1, unit: 'pint', item: 'cherry tomatoes, halved' },
      { quantity: 1, unit: '', item: 'jalapeño, finely chopped' },
      { quantity: 0.25, unit: 'cup', item: 'red onion, finely chopped' },
      { quantity: 0.5, unit: 'lime', item: 'Juice of lime' },
      { quantity: 0.125, unit: 'tsp', item: 'salt (for the pico de gallo)' },
      { quantity: 12, unit: 'oz can', item: 'corn kernels, drained' },
      { quantity: 0.5, unit: 'cup', item: 'shredded mozzarella cheese (optional)' }
    ],
    instructions: [
      'Cook the brown rice according to package instructions. When cooking, add the lime zest and salt to the water so the rice absorbs the flavor. Once cooked, set aside to cool slightly before dividing into meal-prep containers.',
      'In a skillet over medium heat, cook the ground turkey. Break it up with a spatula and cook until it\'s no longer pink (about 10 minutes).',
      'Sprinkle the taco seasoning over the cooked turkey, then pour in the water. Stir and let the mixture simmer for a few minutes until the sauce thickens. Remove from heat and allow to cool slightly.',
      'While the turkey is cooking or cooling, prepare the pico de gallo: in a bowl, combine halved cherry tomatoes, chopped jalapeño, red onion, lime juice, and salt. Stir until well mixed.',
      'Divide the cooked rice, seasoned turkey, drained corn, and pico de gallo evenly among four 2-cup meal prep containers.',
      'Sprinkle shredded mozzarella cheese on top of each bowl if using.'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free'],
    healthTags: ['High-Protein'],
  },

  {
    id: '16',
    title: 'Chicken & Veggie Fried Rice',
    image: '/chicken-veggie-fried-rice.jpg',
    cuisines: ['Asian'],
    mealType: 'lunch',
    mealPrepDuration: 4,
    difficulty: 'easy',
    cookTime: 20,
    servings: 1,
    rating: 4.8,
    source: 'Gimme Delicious',
    sourceUrl: 'https://gimmedelicious.com/healthy-chicken-veggie-fried-rice-meal-prep/',
    ingredients: [
      { quantity: 2, unit: 'tablespoons', item: 'olive oil (or sesame oil or another oil of choice)' },
      { quantity: 1, unit: 'lb', item: 'chicken breast, cut into bite-sized cubes' },
      { quantity: 0.5, unit: 'cup', item: 'diced onion' },
      { quantity: 1, unit: '', item: 'red or green bell pepper, diced' },
      { quantity: 1, unit: 'cup', item: 'frozen peas and carrots blend' },
      { quantity: 1, unit: 'clove', item: 'garlic, minced' },
      { quantity: 3, unit: 'tablespoons', item: 'low-sodium soy sauce' },
      { quantity: null, unit: '', item: 'Salt and pepper, to taste' },
      { quantity: 4, unit: 'cups', item: 'cooked brown rice' }
    ],
    instructions: [
     'Heat the oil in a large skillet over medium-high heat.',
     'Add the cubed chicken, season with salt and pepper, and cook until the chicken is just cooked through.',
     'Add the onion, bell pepper, peas and carrots, and garlic. Sauté for about 1 minute.',
     'Add the cooked brown rice and the soy sauce. Stir-fry for 2–3 minutes until everything is heated and combined.',
     'Let the mixture cool for about 5 minutes.',
     'Divide the fried rice into 4 meal-prep containers. Drizzle with sriracha if you like some spice.',
     'Allow the rice to cool fully before refrigerating or freezing.',
     'To reheat: Microwave on medium-high heat for 2 minutes or until steaming.'
    ],
    dietaryTags: ['Nut-Free', 'Gluten-Free', 'Dairy-Free'],
    healthTags: ['High-Protein'],
  },

  {
    id: '17',
    title: 'Mac & Cheese',
    image: '/mac-and-cheese.jpg',
    cuisines: ['American'],
    mealType: 'lunch',
    mealPrepDuration: 4,
    difficulty: 'medium',
    cookTime: 25,
    servings: 1,
    rating: 4.8,
    source: 'Work Week Lunch',
    sourceUrl: 'https://workweeklunch.com/mac-n-cheese/',
    ingredients: [
      { quantity: null, unit: '', item: 'Cooking spray' },
      { quantity: 8, unit: 'oz', item: 'short pasta (like penne, cavatappi, elbow macaroni)' },
      { quantity: 1, unit: 'head', item: 'broccoli, chopped into florets (about 3 cups)' },
      { quantity: 2, unit: 'tablespoons', item: 'unsalted butter' },
      { quantity: 2, unit: 'tablespoons', item: 'all-purpose flour' },
      { quantity: 1, unit: 'cup', item: 'warm milk' },
      { quantity: 2, unit: 'cups', item: 'shredded cheese (your choice)' },
      { quantity: 1, unit: 'teaspoon', item: 'chipotle powder' },
      { quantity: null, unit: '', item: 'Salt and pepper, to taste' },
      { quantity: 0.25, unit: 'cup', item: 'breadcrumbs (optional, for topping)' }
    ],
    instructions: [
     'Preheat oven to 400°F and grease a 9x9 baking dish with cooking spray.',
     'Bring a large pot of water to boil, add salt, then cook the pasta. Add the broccoli to the pot about 2–3 minutes before the pasta is al dente so the broccoli cooks too. Drain both.',
     'In a saucepan over medium-low heat, melt the butter. Add the flour and stir for 2–3 minutes to make a roux.',
     'Slowly whisk in the warm milk, raising heat a little, until mixture thickens and smooths out.',
     'Stir in the shredded cheese until fully melted, then add chipotle powder, salt, and pepper. Adjust seasoning to taste.',
     'Combine the pasta and broccoli with the cheese sauce in the baking dish. Mix everything together evenly.',
     'If using, sprinkle the breadcrumbs on top.',
     'Bake uncovered for 15 minutes, or until the top is golden. (You can also skip baking and serve it straight from the pot.)',
     'Let cool slightly, then divide into meal-prep containers when ready.'
    ],
    dietaryTags: ['Nut-Free', 'Vegetarian'],
    healthTags: ['High-Protein'],
  },

  {
    id: '18',
    title: 'Ramen',
    image: '/ramen.jpg',
    cuisines: ['Asian'],
    mealType: 'dinner',
    mealPrepDuration: 5,
    difficulty: 'medium',
    cookTime: 540,
    servings: 12,
    rating: 4.8,
    source: 'Pinch of Yum',
    sourceUrl: 'https://pinchofyum.com/quick-homemade-ramen',
    ingredients: [
      { quantity: 1, unit: 'tablespoon', item: 'sesame oil' },
      { quantity: 3, unit: 'teaspoons', item: 'grated ginger' },
      { quantity: 4, unit: 'teaspoons', item: 'grated garlic' },
      { quantity: 4, unit: 'cups', item: 'broth (vegetable or chicken)' },
      { quantity: 4, unit: 'cups', item: 'water' },
      { quantity: 1, unit: 'ounce', item: 'dried shiitake mushrooms' },
      { quantity: 2, unit: 'packages', item: 'instant ramen (noodles only)' },
      { quantity: 0.5, unit: 'cup', item: 'chopped scallions or chives' },
      { quantity: 2, unit: 'cups', item: 'chopped kale (or spinach)' },
      { quantity: 1, unit: 'cup', item: 'shredded carrots (or another vegetable like bok choy)' },
      { quantity: null, unit: '', item: 'Sriracha (to taste)' },
      { quantity: null, unit: '', item: 'Crunchy golden panko crumbs (for topping)' }
    ],
    instructions: [
      'Heat the sesame oil in a large skillet over medium-low heat. Add the garlic and ginger, and stir-fry for about 2 minutes until soft and fragrant.',
      'Add the broth and water, bring to a simmer, then add the dried shiitake mushrooms. Simmer for about 10 minutes, until the mushrooms soften and the broth becomes flavorful.',
      'Add the instant ramen noodles to the hot liquid. Simmer for another ~5 minutes, until the noodles soften. Add the scallions and stir gently.',
      'Remove from heat, then stir in the chopped kale and shredded carrots.',
      'Serve topped with crunchy panko crumbs. Add soft-boiled egg, chili oil, hot sauce, or extra sesame oil if desired.'
    ],
    dietaryTags: ['Nut-Free', 'Dairy-Free', 'Gluten-Free'],
    healthTags: [],
  },

  {
    id: '19',
    title: 'Chicken Stir Fry',
    image: '/chicken-stir-fry.jpg',
    cuisines: ['Asian'],
    mealType: 'dinner',
    mealPrepDuration: 4,
    difficulty: 'easy',
    cookTime: 18,
    servings: 1,
    rating: 4.8,
    source: 'Mom on Timeout',
    sourceUrl: 'https://www.momontimeout.com/easy-chicken-stir-fry-recipe/#recipe',
    ingredients: [
      { quantity: 1, unit: 'lb', item: 'boneless, skinless chicken breast, cut into 1-inch cubes' },
      { quantity: null, unit: '', item: 'Salt and pepper, to taste' },
      { quantity: 2, unit: 'tablespoons', item: 'olive oil (divided)' },
      { quantity: 2, unit: 'cups', item: 'broccoli florets' },
      { quantity: 0.5, unit: '', item: 'yellow bell pepper, cut into 1-inch pieces' },
      { quantity: 0.5, unit: '', item: 'red bell pepper, cut into 1-inch pieces' },
      { quantity: 0.5, unit: 'cup', item: 'baby carrots, sliced' },
      { quantity: 2, unit: 'teaspoons', item: 'minced ginger' },
      { quantity: 2, unit: 'garlic cloves', item: 'minced' },
      { quantity: 1, unit: 'tablespoon', item: 'cornstarch' },
      { quantity: 2, unit: 'tablespoons', item: 'cold water' },
      { quantity: 0.25, unit: 'cup', item: 'low-sodium chicken broth' },
      { quantity: 3, unit: 'tablespoons', item: 'low-sodium soy sauce' },
      { quantity: 0.25, unit: 'cup', item: 'honey' },
      { quantity: 1, unit: 'tablespoon', item: 'toasted sesame oil' },
      { quantity: 0.5, unit: 'teaspoon', item: 'crushed red pepper flakes (optional)' }
    ],
    instructions: [
      'In a bowl, whisk together the cornstarch and cold water, then mix in the chicken broth, soy sauce, honey, sesame oil, and red pepper flakes (if using).',
      'Heat 1 tablespoon olive oil in a large skillet or wok over medium-high heat.',
      'Add the cubed chicken, season with salt and pepper, and cook for 3–5 minutes until cooked through. Remove chicken and set aside.',
      'Add the remaining tablespoon of olive oil to the skillet and reduce heat to medium.',
      'Add broccoli, bell peppers, and carrots. Stir-fry until crisp-tender. Add ginger and garlic and cook 1 more minute.',
      'Return chicken to the skillet.',
      'Pour the prepared sauce over everything and stir to combine.',
      'Bring to a boil and let it cook for 1 minute to thicken.',
      'Serve alone or over rice/noodles.'
    ],
    dietaryTags: ['Nut-Free', 'Dairy-Free'],
    healthTags: ['High-Protein'],
  },

  {
    id: '20',
    title: 'Roasted Vegetable Salad',
    image: '/roasted-vegetable-salad.jpg',
    cuisines: ['Mediterranean'],
    mealType: 'dinner',
    mealPrepDuration: 4,
    difficulty: 'medium',
    cookTime: 80,
    servings: 1,
    rating: 4.8,
    source: 'Budget Bytes',
    sourceUrl: 'https://www.budgetbytes.com/roasted-vegetable-salad-meal-prep/',
    ingredients: [
      { quantity: 0.25, unit: 'teaspoon', item: 'garlic powder' },
      { quantity: 0.25, unit: 'teaspoon', item: 'onion powder' },
      { quantity: 0.5, unit: 'teaspoon', item: 'dried dill' },
      { quantity: 0.5, unit: 'teaspoon', item: 'dried parsley' },
      { quantity: 0.25, unit: 'teaspoon', item: 'salt' },
      { quantity: null, unit: '', item: 'Freshly cracked pepper (to taste)' },
      { quantity: 0.25, unit: 'cup', item: 'tahini' },
      { quantity: 0.25, unit: 'cup', item: 'warm water' },
      { quantity: 3, unit: 'tablespoons', item: 'lemon juice' },
      { quantity: 1, unit: 'cup', item: 'quinoa' },
      { quantity: 1.75, unit: 'cups', item: 'water (for cooking quinoa)' },
      { quantity: 1, unit: 'pint', item: 'grape tomatoes' },
      { quantity: 8, unit: 'oz', item: 'mushrooms' },
      { quantity: 1, unit: '', item: 'zucchini' },
      { quantity: 1, unit: '', item: 'yellow squash' },
      { quantity: 1, unit: '', item: 'red onion' },
      { quantity: 2, unit: 'tablespoons', item: 'olive oil' },
      { quantity: 1, unit: 'teaspoon', item: 'dreid oregano' },
      { quantity: 0.25, unit: 'teaspoon', item: 'garlic powder' },
      { quantity: 0.25, unit: 'teaspoon', item: 'salt' },
      { quantity: 4, unit: 'cups', item: 'fresh spinach' },
      { quantity: 0.5, unit: 'cup', item: 'hummus' }
    ],
    instructions: [
      'In a small bowl, whisk together garlic powder, onion powder, dried dill, dried parsley, salt, pepper, tahini, warm water, and lemon juice until smooth. Refrigerate the dressing while you prepare the rest of the salad.',
      'Rinse the quinoa in a fine mesh sieve, then place in a small pot with 1.75 cups of water. Bring to a boil, then reduce heat to low, cover, and simmer for 15 minutes.',
      'After simmering, remove the pot from heat and let the quinoa rest, covered, for 5 minutes. Then spread the quinoa in a shallow dish to cool more quickly, and refrigerate until ready to assemble.',
      'Preheat the oven to 400°F. On a baking sheet, lay out the grape tomatoes, sliced red onion, sliced zucchini, sliced yellow squash, and halved mushrooms in a single layer (use two baking sheets if needed).',
      'Drizzle the vegetables with olive oil, then sprinkle with oregano, garlic powder, and salt. Use your hands to toss until everything is evenly coated.',
      'Roast the vegetables in the oven, stirring every 15 minutes, until they are browned on the edges (about 40 minutes).',
      'Let the roasted vegetables cool for about 10 minutes at room temperature.',
      'To assemble: In each of four meal prep containers, place one heaping cup of spinach. On top of the spinach, add ½ cup of the cooked and cooled quinoa. Divide the roasted vegetables evenly among the containers. Add 2 tablespoons of hummus to each.',
      'Divide the dressing into four small containers.',
      'Refrigerate the meal-prep salads and the dressing for up to 4 days.'
    ],
    dietaryTags: ['Dairy-Free', 'Vegan', 'Vegetarian'],
    healthTags: ['High-Protein', 'Low-Cholesterol'],
  },








]
