import type { Recipe } from '@/types/recipe'

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Classic Margherita Pizza',
    image: '/margherita-pizza-fresh-basil-mozzarella.jpg',
    cuisines: ['Italian'],
    difficulty: 'easy',
    cookTime: 25,
    servings: 4,
    rating: 4.8,
    source: 'Food Blogger Pro',
    sourceUrl: 'https://example.com/recipe/margherita-pizza',
    ingredients: [
      { name: 'Pizza dough', amount: 1, unit: 'ball' },
      { name: 'San Marzano tomatoes', amount: 400, unit: 'g' },
      { name: 'Fresh mozzarella', amount: 250, unit: 'g' },
      { name: 'Fresh basil', amount: 10, unit: 'leaves' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Salt & pepper', amount: 1, unit: 'to taste' },
    ],
    instructions: [
      'Preheat oven to 475°F (245°C)',
      'Stretch dough to desired thickness',
      'Spread tomato sauce evenly',
      'Tear mozzarella and distribute on top',
      'Drizzle with olive oil',
      'Bake for 12-15 minutes until crust is golden',
      'Add fresh basil after baking',
      'Season with salt and pepper to taste',
    ],
    dietaryTags: ['Vegetarian'],
    healthTags: [],
  },
  {
    id: '2',
    title: 'Thai Green Curry',
    image: '/thai-green-curry-coconut-milk-chicken.jpg',
    cuisines: ['Thai'],
    difficulty: 'medium',
    cookTime: 35,
    servings: 4,
    rating: 4.7,
    source: 'Asian Kitchen Secrets',
    sourceUrl: 'https://example.com/recipe/thai-green-curry',
    ingredients: [
      { name: 'Chicken breast', amount: 500, unit: 'g' },
      { name: 'Green curry paste', amount: 3, unit: 'tbsp' },
      { name: 'Coconut milk', amount: 400, unit: 'ml' },
      { name: 'Thai basil', amount: 20, unit: 'leaves' },
      { name: 'Green chilies', amount: 2, unit: 'whole' },
      { name: 'Lime juice', amount: 2, unit: 'tbsp' },
      { name: 'Fish sauce', amount: 1, unit: 'tbsp' },
      { name: 'Rice', amount: 2, unit: 'cups' },
    ],
    instructions: [
      'Cook rice according to package directions',
      'Cut chicken into bite-sized pieces',
      'Heat coconut milk in a wok over medium heat',
      'Add curry paste and stir well',
      'Add chicken and cook for 10 minutes',
      'Add basil and chilies',
      'Finish with lime juice and fish sauce',
      'Serve over rice',
    ],
    dietaryTags: [],
    healthTags: ['High Protein'],
  },
  {
    id: '3',
    title: 'Mediterranean Quinoa Bowl',
    image: '/mediterranean-quinoa-bowl-fresh-vegetables-feta.jpg',
    cuisines: ['Mediterranean'],
    difficulty: 'easy',
    cookTime: 20,
    servings: 2,
    rating: 4.6,
    source: 'Healthy Eats Daily',
    sourceUrl: 'https://example.com/recipe/quinoa-bowl',
    ingredients: [
      { name: 'Quinoa', amount: 1, unit: 'cup' },
      { name: 'Cucumber', amount: 1, unit: 'whole' },
      { name: 'Tomatoes', amount: 2, unit: 'whole' },
      { name: 'Red onion', amount: 0.5, unit: 'whole' },
      { name: 'Feta cheese', amount: 100, unit: 'g' },
      { name: 'Olive oil', amount: 3, unit: 'tbsp' },
      { name: 'Lemon', amount: 1, unit: 'whole' },
      { name: 'Kalamata olives', amount: 50, unit: 'g' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Dice cucumber, tomatoes, and red onion',
      'Combine cooked quinoa with vegetables',
      'Crumble feta cheese over top',
      'Whisk olive oil with lemon juice',
      'Pour dressing over bowl',
      'Top with kalamata olives',
      'Serve at room temperature',
    ],
    dietaryTags: ['Vegetarian', 'Gluten-Free'],
    healthTags: ['Low Carb', 'High Protein'],
  },
  {
    id: '4',
    title: 'Spicy Chicken Tikka Masala',
    image: '/chicken-tikka-masala-creamy-tomato-sauce.jpg',
    cuisines: ['Indian'],
    difficulty: 'hard',
    cookTime: 50,
    servings: 4,
    rating: 4.9,
    source: 'Curry Kitchen',
    sourceUrl: 'https://example.com/recipe/tikka-masala',
    ingredients: [
      { name: 'Chicken breast', amount: 800, unit: 'g' },
      { name: 'Greek yogurt', amount: 200, unit: 'g' },
      { name: 'Tikka masala sauce', amount: 400, unit: 'ml' },
      { name: 'Heavy cream', amount: 200, unit: 'ml' },
      { name: 'Ginger garlic paste', amount: 2, unit: 'tbsp' },
      { name: 'Onion', amount: 2, unit: 'large' },
      { name: 'Cilantro', amount: 30, unit: 'g' },
      { name: 'Rice', amount: 2, unit: 'cups' },
    ],
    instructions: [
      'Marinate chicken in yogurt and spices for 30 minutes',
      'Cook rice separately',
      'Grill or pan-fry marinated chicken until cooked',
      'Dice onions and sauté in oil',
      'Add ginger-garlic paste',
      'Pour in tikka masala sauce',
      'Add cooked chicken pieces',
      'Simmer and add cream',
      'Garnish with cilantro',
      'Serve over rice',
    ],
    dietaryTags: [],
    healthTags: ['High Protein'],
  },
  {
    id: '5',
    title: 'Fresh Summer Salad with Grilled Salmon',
    image: '/grilled-salmon-fresh-summer-salad.jpg',
    cuisines: ['Mediterranean'],
    difficulty: 'medium',
    cookTime: 30,
    servings: 2,
    rating: 4.8,
    source: 'Healthy Cooking',
    sourceUrl: 'https://example.com/recipe/salmon-salad',
    ingredients: [
      { name: 'Salmon fillet', amount: 400, unit: 'g' },
      { name: 'Mixed greens', amount: 200, unit: 'g' },
      { name: 'Cherry tomatoes', amount: 150, unit: 'g' },
      { name: 'Avocado', amount: 1, unit: 'whole' },
      { name: 'Lemon', amount: 1, unit: 'whole' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
      { name: 'Balsamic vinegar', amount: 1, unit: 'tbsp' },
      { name: 'Sea salt', amount: 1, unit: 'tsp' },
    ],
    instructions: [
      'Season salmon with salt and lemon',
      'Grill salmon skin-side down for 4 minutes',
      'Flip and cook for another 3-4 minutes',
      'Wash and dry mixed greens',
      'Halve cherry tomatoes',
      'Slice avocado',
      'Arrange greens on plate',
      'Top with tomatoes and avocado',
      'Place salmon on top',
      'Drizzle with oil and vinegar',
    ],
    dietaryTags: ['Gluten-Free', 'Dairy-Free'],
    healthTags: ['High Protein', 'Low Carb'],
  },
  {
    id: '6',
    title: 'Vegan Buddha Bowl',
    image: '/vegan-buddha-bowl-colorful-vegetables.jpg',
    cuisines: ['American'],
    difficulty: 'easy',
    cookTime: 25,
    servings: 2,
    rating: 4.5,
    source: 'Plant Based Kitchen',
    sourceUrl: 'https://example.com/recipe/buddha-bowl',
    ingredients: [
      { name: 'Quinoa', amount: 1, unit: 'cup' },
      { name: 'Sweet potato', amount: 1, unit: 'large' },
      { name: 'Chickpeas', amount: 400, unit: 'g' },
      { name: 'Kale', amount: 200, unit: 'g' },
      { name: 'Beetroot', amount: 1, unit: 'medium' },
      { name: 'Tahini', amount: 3, unit: 'tbsp' },
      { name: 'Lemon', amount: 1, unit: 'whole' },
      { name: 'Olive oil', amount: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Cube sweet potato and roast at 400°F for 20 minutes',
      'Roast chickpeas with spices until crispy',
      'Massage kale with olive oil',
      'Slice cooked beetroot',
      'Make tahini dressing with lemon juice',
      'Arrange all components in bowl',
      'Drizzle with tahini dressing',
    ],
    dietaryTags: ['Vegan', 'Gluten-Free'],
    healthTags: ['High Protein', 'Low Cholesterol'],
  },
]
